name: Apache CI CD Workflow

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Apache Docker image
        run: docker pull httpd:alpine

      - name: Run Apache container
        run: docker run -d --name apache-container -p 8080:80 httpd:aplpine

      - name: Check Apache container logs
        run: docker logs apache-container

      # Add more steps as needed, such as testing, deployment, etc.
